### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by Remy2072** [iBadr49/Portfolio-v2#22]
Op het kleinste mobiele scherm is de site niet helemaal responsive als iemand op een iPhone SE de website inlaad dat ziet hij / zij een header die te dicht op elkaar zit.
<img width="369" alt="Scherm­afbeelding 2024-06-05 om 10 53 59" src="https://github.com/iBadr49/Portfolio-v2/assets/70781820/1e4f2416-4155-44d8-9e45-3ccb4f64f214">

**Comment by iBadr49** [comment]
Dankjewel voor de feedback het is nu responsive ..
